# Implimentation of Multi Layer Perceptron

In [1]:
import random
import numpy as np

# Class-Neural Network

In [17]:
class NeuralNetworkMLP():
    def __init__(self, input_size, output_size):
         random.seed(2)
        self.synaptic_weights = 2 * np.random.random((input_size, output_size)) - 1

    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def __sigmoid_derivative(self, x):
        return x * (1 - x)

    def think(self, inputs):
        return self.__sigmoid(np.dot(inputs, self.synaptic_weights))

    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in range(number_of_training_iterations):
            output = self.think(training_set_inputs)
            error = training_set_outputs - output
            adjustment = np.dot(training_set_inputs.T, error * self.__sigmoid_derivative(output))
            # Adjust weights
            self.synaptic_weights += adjustment / len(training_set_inputs)


# Initialize the Network

In [18]:
if __name__ == '__main__':
    # Initialize a neural network with 3 input and 2 output connections
    neural_network = NeuralNetworkMLP(3, 2)
    print('\nRandom starting weights:\n')
    print(neural_network.synaptic_weights)

    training_set_inputs = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
    training_set_outputs = np.array([[0, 1], [1, 0], [1, 1], [0, 0]])


Random starting weights:

[[-0.42473201  0.65740781]
 [-0.11692336  0.87512381]
 [ 0.51087379 -0.17979751]]


# Train the Neural Network

In [19]:
# Train the network
print('********************* Neural Network Training Phase *****************')
neural_network.train(training_set_inputs, training_set_outputs, 10000)
print('\nNew weights after training\n')
print(neural_network.synaptic_weights)
print()

# Test the network
print('\nConsidering the new situation [1, 0, 0] --> ?:')
print()
print(neural_network.think(np.array([1, 0, 0])))


********************* Neural Network Training Phase *****************
New weights after training

[[ 8.23451636  0.21580413]
 [-0.21518101 -8.23418355]
 [-3.90487028  3.90433164]]

Considering the new situation [1, 0, 0] --> ?:

[0.99973474 0.55374262]


# Class-Neural Network With Hidden Layer

In [28]:
class NeuralNetworkMLP_H():
    def __init__(self, input_size, hidden_size, output_size):
        random.seed(2)
        self.synaptic_weights_input_hidden = 2 * np.random.random((input_size, hidden_size)) - 1
        self.synaptic_weights_hidden_output = 2 * np.random.random((hidden_size, output_size)) - 1

    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def __sigmoid_derivative(self, x):
        return x * (1 - x)

    def think(self, inputs):
        hidden_output = self.__sigmoid(np.dot(inputs, self.synaptic_weights_input_hidden))
        output = self.__sigmoid(np.dot(hidden_output, self.synaptic_weights_hidden_output))
        return output

    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in range(number_of_training_iterations):
            hidden_layer_output = self.__sigmoid(np.dot(training_set_inputs, self.synaptic_weights_input_hidden))
            output = self.__sigmoid(np.dot(hidden_layer_output, self.synaptic_weights_hidden_output))
            output_error = training_set_outputs - output
            hidden_layer_error = output_error.dot(self.synaptic_weights_hidden_output.T)
            output_delta = output_error * self.__sigmoid_derivative(output)
            hidden_layer_delta = hidden_layer_error * self.__sigmoid_derivative(hidden_layer_output)
            self.synaptic_weights_hidden_output += hidden_layer_output.T.dot(output_delta)
            self.synaptic_weights_input_hidden += training_set_inputs.T.dot(hidden_layer_delta)


# Initialize the Network

In [29]:

if __name__ == '__main__':
    neural_network = NeuralNetworkMLP_H(3, 4, 1)
    print('\nRandom starting weights for input to hidden layer:\n')
    print(neural_network.synaptic_weights_input_hidden)
    print('\n\nRandom starting weights for hidden to output layer:\n')
    print(neural_network.synaptic_weights_hidden_output)
    training_set_inputs = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
    training_set_outputs = np.array([[0, 1, 1, 0]]).T



Random starting weights for input to hidden layer:

[[ 0.62685604  0.97486671  0.59866858 -0.59514644]
 [-0.05353667 -0.13716162 -0.41372054 -0.15235189]
 [ 0.49894876  0.86884436  0.28520447  0.51836411]]


Random starting weights for hidden to output layer:

[[-0.25378973]
 [-0.35383671]
 [-0.40416531]
 [ 0.93230652]]


# Train the Neural Network

In [30]:
print('********************* Neural Network Training Phase *****************')
neural_network.train(training_set_inputs, training_set_outputs, 10000)
print('\nNew weights for input to hidden layer after training:\n')
print(neural_network.synaptic_weights_input_hidden)
print('\nNew weights for hidden to output layer after training:\n')
print(neural_network.synaptic_weights_hidden_output)
print()
print('\nConsidering the new situation [1, 0, 0] --> ? :\t',neural_network.think(np.array([1, 0, 0])))

********************* Neural Network Training Phase *****************

New weights for input to hidden layer after training:

[[ -8.79583896  -7.16925669 -10.39456621  11.31598625]
 [  0.34790108   0.31917228   0.33063837  -0.34332535]
 [  3.74439647   2.93010321   4.56217421  -5.01745622]]

New weights for hidden to output layer after training:

[[-1.7439883 ]
 [-0.93219157]
 [-3.34434982]
 [ 5.39438342]]


Considering the new situation [1, 0, 0] --> ? :	 [0.99547334]
